@MyBuddy.Api_HostAddress = http://localhost:5277

GET {{MyBuddy.Api_HostAddress}}/health
Accept: text/plain

###

GET {{MyBuddy.Api_HostAddress}}/openapi/v1.json
Accept: application/json

###
